"""Public PyPageKit exception hierarchy."""

from .domain import (
    DomainError,
    InvalidAriaAttributeNameError,
    InvalidAttributeError,
    InvalidClassTokenError,
    InvalidContainerChildError,
    InvalidDataAttributeNameError,
    InvalidHeadingLevelError,
    InvalidImageSourceError,
    InvalidLinkHrefError,
    InvalidPageContentError,
    InvalidPageLanguageError,
    InvalidPageTitleError,
    PyPageKitError,
    ValidationError,
)
from .rendering import (
    InvalidHtmlAttributeNameError,
    InvalidHtmlTagError,
    RenderingError,
    SecurityError,
    SerializationError,
    UnsafeUrlError,
    UnsupportedAttributeValueError,
    UnsupportedNodeError,
)

__all__ = [
    "DomainError",
    "InvalidAriaAttributeNameError",
    "InvalidAttributeError",
    "InvalidClassTokenError",
    "InvalidContainerChildError",
    "InvalidDataAttributeNameError",
    "InvalidHeadingLevelError",
    "InvalidHtmlAttributeNameError",
    "InvalidHtmlTagError",
    "InvalidImageSourceError",
    "InvalidLinkHrefError",
    "InvalidPageContentError",
    "InvalidPageLanguageError",
    "InvalidPageTitleError",
    "PyPageKitError",
    "RenderingError",
    "SecurityError",
    "SerializationError",
    "UnsafeUrlError",
    "UnsupportedAttributeValueError",
    "UnsupportedNodeError",
    "ValidationError",
]
