"""Public PyPageKit exception hierarchy."""

from .component import (
    ComponentCycleError,
    ComponentError,
    ComponentResolutionDepthError,
    InvalidComponentResultError,
)
from .domain import (
    DomainError,
    DuplicateLayoutRegionError,
    InvalidAriaAttributeNameError,
    InvalidAttributeError,
    InvalidClassTokenError,
    InvalidContainerChildError,
    InvalidDataAttributeNameError,
    InvalidHeadingLevelError,
    InvalidImageSourceError,
    InvalidLayoutError,
    InvalidLayoutRegionChildError,
    InvalidLayoutRegionNameError,
    InvalidLayoutRegionResultError,
    InvalidLinkHrefError,
    InvalidPageContentError,
    InvalidPageLanguageError,
    InvalidPageTitleError,
    PyPageKitError,
    ValidationError,
)
from .rendering import (
    InvalidHtmlAttributeNameError,
    InvalidHtmlTagError,
    RenderingError,
    SecurityError,
    SerializationError,
    UnsafeUrlError,
    UnsupportedAttributeValueError,
    UnsupportedNodeError,
)

__all__ = [
    "ComponentCycleError",
    "ComponentError",
    "ComponentResolutionDepthError",
    "DomainError",
    "DuplicateLayoutRegionError",
    "InvalidAriaAttributeNameError",
    "InvalidAttributeError",
    "InvalidClassTokenError",
    "InvalidComponentResultError",
    "InvalidContainerChildError",
    "InvalidDataAttributeNameError",
    "InvalidHeadingLevelError",
    "InvalidHtmlAttributeNameError",
    "InvalidHtmlTagError",
    "InvalidImageSourceError",
    "InvalidLayoutError",
    "InvalidLayoutRegionChildError",
    "InvalidLayoutRegionNameError",
    "InvalidLayoutRegionResultError",
    "InvalidLinkHrefError",
    "InvalidPageContentError",
    "InvalidPageLanguageError",
    "InvalidPageTitleError",
    "PyPageKitError",
    "RenderingError",
    "SecurityError",
    "SerializationError",
    "UnsafeUrlError",
    "UnsupportedAttributeValueError",
    "UnsupportedNodeError",
    "ValidationError",
]
