"""PyPageKit public package."""

from .domain import (
    Attributes,
    Component,
    ComponentRef,
    Container,
    Content,
    Fragment,
    Heading,
    Image,
    Layout,
    LayoutRegion,
    Link,
    Navigation,
    NavigationItem,
    Node,
    Page,
    Paragraph,
    Route,
    Site,
    Sitemap,
    SitemapEntry,
    Slot,
    SlotBindings,
    SlottedComponent,
    Text,
    bind_slots,
)

__version__ = "0.4.0b1"

__all__ = [
    "Attributes",
    "Component",
    "ComponentRef",
    "Container",
    "Content",
    "Fragment",
    "Heading",
    "Image",
    "Layout",
    "LayoutRegion",
    "Link",
    "Navigation",
    "NavigationItem",
    "Node",
    "Page",
    "Paragraph",
    "Route",
    "Site",
    "Sitemap",
    "SitemapEntry",
    "Slot",
    "SlotBindings",
    "SlottedComponent",
    "Text",
    "__version__",
    "bind_slots",
]
